### ISSUE TITLE
关于字幕压制

### ISSUE THREAD

**Issue by lchypwx** [djj45/asoul#1]
“libpass库对太多的弹幕优化不行，导致cpu跑不满，瓶颈在cpu，硬件加速没有意义”
此处直接用n卡压制弹幕如何，2060压制速度三到四倍速左右（10875h用libx264压制只有0.8倍速）
附上我的命令：ffmpeg -hwaccel cuda -c:v h264_cuvid -i input.flv -vf subtitles=input.ass  -c:v h264_nvenc  -b:v 8000k -c:a copy  output.flv

**Comment by djj45** [comment]
不对呀，asoul的40%屏弹幕，贾布的设置，你的命令，5600x加2060才1.3x

**Comment by djj45** [comment]
> “libpass库对太多的弹幕优化不行，导致cpu跑不满，瓶颈在cpu，硬件加速没有意义” 此处直接用n卡压制弹幕如何，2060压制速度三到四倍速左右（10875h用libx264压制只有0.8倍速） 附上我的命令：ffmpeg -hwaccel cuda -c:v h264_cuvid -i input.flv -vf subtitles=input.ass  -c:v h264_nvenc  -b:v 8000k -c:a copy  output.flv
不对呀，asoul的40%屏弹幕，贾布的设置，你的命令，5600x加2060才1.3x

**Comment by djj45** [comment]
cpu占用百分之40，显卡占用百分之30，几个au都测试过类似的命令了，快不了

**Comment by lchypwx** [comment]
> cpu占用百分之40，显卡占用百分之30，几个au都测试过类似的命令了，快不了

会不会是没装cuda：https://developer.nvidia.com/cuda-downloads
我这边cpu只占了13%，显卡几乎跑满

**Comment by djj45** [comment]
> 

你用测试用的弹幕和录播是asoul的吗，弹幕设置是什么，子号边框阴影是多少，是不是粗体，显示范围是多少，稳定下来（压两三分钟之后）的压制速度是多少

**Comment by djj45** [comment]
> > cpu占用百分之40，显卡占用百分之30，几个au都测试过类似的命令了，快不了
> 
> 会不会是没装cuda：https://developer.nvidia.com/cuda-downloads 我这边cpu只占了13%，显卡几乎跑满

你用测试用的弹幕和录播是asoul的吗，弹幕设置是什么，子号边框阴影是多少，是不是粗体，显示范围是多少，稳定下来（压两三分钟之后）的压制速度是多少

**Comment by lchypwx** [comment]
是的，字号43，阴影描边0，不透明度60，粗体，显示区域40，稳定下来3倍左右
加了描边确实会慢好多，和你说的速度差不多，这点疏忽了

**Comment by djj45** [comment]
> 是的，字号43，阴影描边0，不透明度60，粗体，显示区域40，稳定下来3倍左右 加了描边确实会慢好多，和你说的速度差不多，这点疏忽了

原来影响速度最大的因素是描边，新发现

**Comment by djj45** [comment]
> 是的，字号43，阴影描边0，不透明度60，粗体，显示区域40，稳定下来3倍左右 加了描边确实会慢好多，和你说的速度差不多，这点疏忽了

但是没有描边上传b站效果不好

**Comment by djj45** [comment]
按照b站的码率，1080p超过半屏弹幕效果不如obs录屏
